version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/usr/src/app"
      - "dev-node-modules:/usr/src/app/node_modules"
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: pantry-list-api_pg_1
      DATABASE_USER: pantry_user
      DATABASE_PASS: pantry_pass
      DATABASE_PORT: 5432
      DATABASE_NAME: pantry
    networks:
      - pantry-list

  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=pantry
      - POSTGRES_USER=pantry_user
      - POSTGRES_PASSWORD=pantry_pass
    ports:
      - "5432:5432"
    networks:
      - pantry-list

networks:
  pantry-list:

volumes:
  dev-node-modules:
