version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/usr/src/app"
      - node_modules:/usr/src/app/node_modules
    ports:
      - "4000:4000"
    links:
      - pg
    environment:
      NODE_ENV: development
    depends_on:
      - node_modules

  node_modules:
    image: busybox
    volumes:
      - node_modules:/usr/src/app/node_modules

  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=pantry
      - POSTGRES_USER=pantry_user
      - POSTGRES_PASSWORD=pantry_pass
    ports:
      - "5432:5432"

volumes:
  node_modules:
