version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/usr/src/app"
      - "dev-node-modules:/usr/src/app/node_modules"
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
    networks:
      - pantry-list

  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=pantry
      - POSTGRES_USER=pantry_user
      - POSTGRES_PASSWORD=pantry_pass
    ports:
      - "5432:5432"
    networks:
      - pantry-list

networks:
  pantry-list:

volumes:
  dev-node-modules:
